### ISSUE TITLE
KIMMDY doesnt work for GROMACS-2023

### ISSUE THREAD

**Issue by ehhartmann** [hits-mbm-dev/kimmdy#301]
ValueError: Failed to construct topology from file /hits/fast/mbm/hartmaec/kimmdys/kimmdy/example/alanine_hat_naive/alanine_hat_017/2_equilibrium/equilibrium.tpr with parser <class 'MDAnalysis.topology.TPRParser.TPRParser'>.
Error: Your tpx version is 129, which this parser does not support, yet

**Comment by ehhartmann** [comment]
maybe increasing the version requirement for mdanalysis would be enough be we will have to check whether everything else still works with this setup

**Comment by KRiedmiller** [comment]
The HAT Plugin requires MDAnalysis <= 2.3 atm, but this should change hopefully soon: https://github.com/hits-mbm-dev/HAT_reaction_plugin/issues/10

**Comment by ehhartmann** [comment]
Done in https://github.com/hits-mbm-dev/HAT_reaction_plugin/pull/11
