### ISSUE TITLE
npme and ntmpi mdrun options

### ISSUE THREAD

**Issue by ehhartmann** [hits-mbm-dev/kimmdy#302]
https://github.com/hits-mbm-dev/kimmdy/blob/1fc410a706bc8eb0c0a5ee0f972a175dc2a243cb/src/kimmdy/runmanager.py#L392

Does this line have any reason to exist, @KRiedmiller @jmbuhr ? I would like to specify those through the config file.

**Comment by jmbuhr** [comment]
We can remove them and add them as defaults for `gmx_mdrun_flags`

**Comment by ehhartmann** [comment]
they dont even seem like good defaults. Maybe for github actions but not for a normal run
