### ISSUE TITLE
Full installation instructions missing

### ISSUE THREAD

**Issue by ehhartmann** [hits-mbm-dev/kimmdy#329]
The full installation instructions from the readme are gone. 
They are useful when installing grappa and the hat-plugin, which is not dealt with in the current install instructions.

**Comment by jmbuhr** [comment]
this should be part of the plugin documentation, as the dependencies of grappa and the hat plugin are not direct dependencies of kimmdy. Especially because parts of this are not yet public, so it would only be confusing to be plain and center in the readme.

**Comment by jmbuhr** [comment]
We can could add a separate documentation page for this and link to it from the readme if you want it to be visible straight away.

**Comment by jmbuhr** [comment]
Now over at https://hits-mbm-dev.github.io/kimmdy/guide/how-to/install-ml-plugins.html with updated instructions.
