### ISSUE TITLE
certain improper dihedrals not removed when bond is broken

### ISSUE THREAD

**Issue by jmbuhr** [hits-mbm-dev/kimmdy#362]
for reference: 
![image](https://github.com/hits-mbm-dev/kimmdy/assets/17450586/ac47000c-9df5-485f-941a-4c8ed3b5dbd5)

**Comment by ehhartmann** [comment]
Maybe I should look at my notifications...
Should be fixed in #390 

```
 [ bonds ]
     N     H
     N    CA
    CA    HA
    CA    CB
    CA     C
    CB   HB1
    CB   HB2
    CB   HB3
     C     O
    -C     N
```

the -C N is the connection, so it is just in residuetypes.dat.

Can you confirm that this fixed your issue?
