### ISSUE TITLE
topology: bonds in pairs

### ISSUE THREAD

**Issue by KRiedmiller** [hits-mbm-dev/kimmdy#376]
modify_top produces, without parametrization, a top that contains bonded atoms in the pairs section.

This leads to exploding systems.

**Comment by ehhartmann** [comment]
if one deletes hydrogens only?

**Comment by KRiedmiller** [comment]
top.del_atom seems to break the pairs. Prior, no pairs are bonds, afterwards I find 8 pairs in the bonds

**Comment by KRiedmiller** [comment]
Seems like we never updated the inner dihedrals obj in MultipleDihedrals

https://github.com/hits-mbm-dev/kimmdy/blob/9f9b162c40aaf91f691b3963578030592f0ec0a5/src/kimmdy/topology/topology.py#L553-L558

The new_dihedrals was not put back into the new MultipleDihedral

Not sure how this creates this problem though..
