### ISSUE TITLE
feat: jobscript slurm options part of the config

### ISSUE THREAD

**Issue by jmbuhr** [hits-mbm-dev/kimmdy#419]
Because the chained resubmission uses generate-jobscript, it would be beneficial to make the jobscript slurm options part of the config. This way, one could set the partition, number of cpus, gpus, nodes etc. specifically for each job. Up to now I have just changed the default in templates.py.

_Originally posted by @ehhartmann in https://github.com/hits-mbm-dev/kimmdy/issues/410#issuecomment-2018180306_

**Comment by ehhartmann** [comment]
was about to raise an issue for this :)

**Comment by jmbuhr** [comment]
fixed by https://github.com/hits-mbm-dev/kimmdy/pull/432
